# Generated by Django 5.2 on 2025-04-25 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Platform', models.CharField(choices=[('CISCO', 'CISCO'), ('PALO_ALTO_NETWORKS', 'PALO_ALTO_NETWORKS'), ('CITRIX', 'CITRIX'), ('CHECKPOINT', 'CHECKPOINT'), ('F5', 'F5'), ('JUNIPER', 'JUNIPER'), ('UnKnown', 'UnKnown')], default='UnKnown', max_length=25)),
                ('DeviceName', models.CharField(blank=True, max_length=50, null=True)),
                ('VIPName', models.CharField(blank=True, max_length=255, null=True)),
                ('SourceAddress', models.TextField(blank=True, null=True)),
                ('VIPAddress', models.TextField(blank=True, null=True)),
                ('VIPPort', models.CharField(blank=True, max_length=255, null=True)),
                ('Protocol', models.CharField(blank=True, max_length=25, null=True)),
                ('BackendSrc', models.TextField(blank=True, null=True)),
                ('BackendDst', models.TextField(blank=True, null=True)),
                ('BackendPort', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
