# Generated by Django 5.2.1 on 2025-05-23 01:37

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPCIDRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', netfields.fields.CidrAddressField(blank=True, max_length=43, null=True)),
            ],
        ),
    ]
